### ISSUE TITLE
CheatDB N/A for WindowsBuild 7-1-2021

### ISSUE THREAD

**Issue by ChefZander** [dragonfireclient/dragonfireclient#26] opened 2021-02-12 14:12 UTC
I cant open cheatdb in WindowsBuild 7-1-2021, pls fix, i only get the error "Could not receive any packets"

**Comment by LizzyFleckenstein03** [comment] 2021-03-26 14:07
Duplicate of #30

**Closed as completed by LizzyFleckenstein03** 2021-03-26 14:07 UTC
